### ISSUE TITLE
Broken encryption after updating to 1.11.103

### ISSUE THREAD

**Issue by lucasmz-dev** [flathub/im.riot.Riot#528]
I revoke org.freedesktop.Secrets, and also xdg-run/keyring. Even with this, Element apps usually manage to get an encryption from what seems to be portals. This worked pretty well! I also didn't get as many issues as I did when I didn't do this, where occasionally it decided to break.

![Image](https://github.com/user-attachments/assets/93368066-77f1-45ec-a533-09dbfdf7965a)

Error says the 'encryption' is missing but the keyring is compatible, probably mean encryption key (couldn't get it to show in English)

![Image](https://github.com/user-attachments/assets/b19c3c27-4300-42c0-ae09-cefeac42d46b)

**Comment by schuerg** [comment]
```
# flatpak run im.riot.Riot
[3 zypak-helper] Wait found events, but sd-event found none
[3:0613/103436.610481:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
Loading app config: /app/Element/resources/webapp.asar/config.json
Loading local config: /home/simon/.var/app/im.riot.Riot/config/Element/config.json
Skipping nonexistent file: /home/simon/.var/app/im.riot.Riot/config/Element/config.json
[3:0613/103437.077095:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[3:0613/103437.077133:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
Reached Electron ready state
Starting auto update with base URL: https://packages.element.io/desktop/update/
Ensuring storage is ready
Using storage mode 'encrypted' with backend 'gnome_libsecret'
Failed to decrypt secret Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at SafeStorageWriter.get (file:///app/Element/resources/app.asar/lib/store.js:82:36)
    at Store.getSecret (file:///app/Element/resources/app.asar/lib/store.js:363:35)
    at async getOrCreatePassphrase (file:///app/Element/resources/app.asar/lib/seshat.js:35:34)
    at async IpcMainImpl.<anonymous> (file:///app/Element/resources/app.asar/lib/seshat.js:92:36)
...ciphertext: "XXXXXXXXXXXXXXXXXXXXXXXXXX"
Migrating secret from keytar seshat|@XXXXX:XXXXX|XXXXXXX
```

https://github.com/user-attachments/assets/7936f942-f7c9-48e3-958f-5650ea1585ff

**Comment by rrigby** [comment]
Looks like you can resolve it with Flatseal, by providing the secret session bus name

![Image](https://github.com/user-attachments/assets/3d2cbf68-3d08-4426-9432-fa1d9c80507d)

**Comment by 6e6f6b6f65** [comment]
adding `org.kde.kwalletd6` instead worked for me on KDE.

Arch Linux
Flatpak 1.16.1
Element 1.11.104

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
I was also experiencing this problem until I added `Session bus access` inside the Advanced Permissions section of Flatpak Permissions in KDE System Settings.

I did **not** have to add `org.freedesktop.secrets` or `org.kde.kwalletd6`.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
The computer I have the problem on is Fedora 42 with KDE Plasma. When running Element via Flatpak command-line to capture stdout, it said it could not access the kwalletd6 keyring.

Allowing every D-Bus thing would be like traditional packages, right, or no?

I can do some trial and error again. It may be that I didn't allow `org.kde.kwalletd6` in the proper location.

**Comment by lucasmz-dev** [comment]
it should be under session bus

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
Alright, I did some more monkeying around, removed `Session bus access`, and scrolling further down in the KDE Flatpak Permissions program, added a new Session Bus Policy. I added `org.kde.kwalletd6` with `talk` access solved the launch problem. Thanks to others for pointing out what bus address to add, because I could not identity that syntax from the errors in stdout.

![Image](https://github.com/user-attachments/assets/804baae5-7970-4c93-804e-8be5a784d6a7)

As an aside, I still see a system bus socket error, but no functionality is apparently broken.

>[3:0628/091530.739887:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

...a few lines later in the log reveals:

>Using storage mode 'encrypted' with backend 'kwallet6'

**Comment by purpleidea** [comment]
Seems I have the same issue on Fedora 41 with the flatpak.

"Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory"

```
$ flatpak run im.riot.Riot 
[3:0704/180111.063676:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
/home/user/.var/app/im.riot.Riot/config/Element exists: yes
/home/user/.var/app/im.riot.Riot/config/Riot exists: no
(node:3) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `element-desktop --trace-deprecation ...` to show where the warning was created)
Loading app config: /app/Element/resources/webapp.asar/config.json
Loading local config: /home/user/.var/app/im.riot.Riot/config/Element/config.json
Skipping nonexistent file: /home/user/.var/app/im.riot.Riot/config/Element/config.json
[3:0704/180113.156351:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0704/180113.156435:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Reached Electron ready state
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Opening main window
Ensuring storage is ready
(node:3) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
[3:0704/180117.643283:ERROR:content/browser/browser_main_loop.cc:278] GLib-GObject: ../gobject/gsignal.c:2684: instance '0x1e040280fc00' has no handler with id '2453'
$ echo $?
137

```

**Comment by purpleidea** [comment]
On GNOME I used Flatseal to add:

And while I still see that error in the logs, the application now loads.

<img width="753" height="195" alt="Image" src="https://github.com/user-attachments/assets/e3390a0e-7a62-41b1-affa-6ce1cbb8bcba" />

**Comment by LuccoJ** [comment]
Is it going to be possible to switch back to full encryption, supposing the bug is fixed or worked around in one of the ways stated above, after having click the "Use weaker encryption" (or whatever it was called) button on start, as that was the only way to make it run? Or is that now a one-way street?

**Comment by o-alquimista** [comment]
Flatpak override on the command-line:

```sh
# user installation
flatpak override --user im.riot.Riot --talk-name=org.freedesktop.secrets

# system installation
sudo flatpak override im.riot.Riot --talk-name=org.freedesktop.secrets
```

This creates an override file for either the user (`~/.local/share/flatpak/overrides/im.riot.Riot`) or the system (`/var/lib/flatpak/overrides/im.riot.Riot`):

```
[Session Bus Policy]
org.freedesktop.secrets=talk
```

**Comment by metal3d** [comment]
Same for me, Flatseal resolves the problem by activating socket=session.bus for Dbus in the Element section (the option on the bottom of my below capture):


<img width="774" height="701" alt="Image" src="https://github.com/user-attachments/assets/a6298a9c-e01d-4eb0-9902-8740c9545209" />

**Comment by lucasmz-dev** [comment]
@Mario5Gray I believe I got the name of kdewallet wrong some posts before, if you forgot the d, then it won't work. It's org.kde.kwalletd6.

**Comment by lucasmz-dev** [comment]
Truth is, before getting this error and now, nothing changed. Only the error now shows that you're not encrypting the encryption keys with the system keyring, but it was the same before.

**Comment by solbu** [comment]
> Truth is, before getting this error and now, nothing changed. 
> Only the error now shows that you're not encrypting the encryption keys with the system keyring, but it was the same before.

That may be so, but the error does not say that. It says that it cannot access the keys (It is bloddy annoying that I cannot copy the actual text from the error prompt), and one can cancel or proceed without encryption. 
Meaning no encrypted messages in Matrix. That is how I read that error message.

**Comment by lucasmz-dev** [comment]
Did you try org.kde.kwalletd6 if you're on KDE? or org.kde.kwalletd5 if you're on like KDE 5? it should work then.

> Meaning no encrypted messages in Matrix. That is how I read that error message.

It's not a great message. You still have E2EE, but the Element database is encrypted with just a key that's like on a file I guess, not encrypted using the system keyring (therefore not protected by your user password). If your disk is encrypted, that's fine, otherwise someone can steal your data right away if they have access to your disk. Though, that might not be very protected by your user password, considering how people's passwords usually are. But that's it basically, at rest encryption.

**Comment by seiha011** [comment]
> [@seiha011](https://github.com/seiha011) get Flatseal, go in the settings for Element, and under "Session bus" (all the way down, not the global toggle), you add org.freedesktop.secrets, org.kde.kwalletd6 and org.kde.kwalletd5. That should get things working. You only really need org.freedesktop.secrets since you use gnome

Thanks!

**Comment by lancatlin** [comment]
This command works for me:

```
sudo flatpak override im.riot.Riot --talk-name=org.freedesktop.secrets
```

**Comment by vivlim** [comment]
In Plasma 6, you can enable encryption by:

1. ` System Settings` > `Application Permissions` > `Application Permissions` 
1. Pick `Element` 
1. Click `Manage Flatpak Settings` (button at the upper right) 
1. Scroll down to and expand `Advanced Permissions` 
1. Scroll to `Session Bus Policy` (*not* System Bus Policy) 
1. Click `Add New...`
1. Type `org.freedesktop.secrets` and pick `talk` from the combo box
1. Click `Add New...`
1. Type `org.kde.kwalletd6` and pick `talk` from the combo box
1. Click apply in the bottom right

It should look something like this:

<img width="1996" height="1528" alt="Image" src="https://github.com/user-attachments/assets/cea57745-b624-4903-87a8-679463fd6f19" />

From what I can tell (as an uninformed user, after reading a couple of the issues related to this), doing this also means that Element has access to any secrets that other applications have stored in the keychain, personally I prefer taking that trade-off if it means not storing my encrypted messages in plaintext (where they would presumably be trivially accessible to any software running under my account)

**Comment by lucasmz-dev** [comment]
I don't see how it would protect from system apps, the keyring is the same

It's literally just some basic protection for the keys for the encryption at rest for people who don't encrypt their disk

They probably could've made the Portals system more resistant by not making it rely on the existing keyring or something.

(Why couldn't they also wrap some sort of keyring for each sandbox encrypted by a key from the portal?)

**Comment by lucasmz-dev** [comment]
I wouldn't depend on encryption for that kind of protection, it really is a job for sandboxing. the thing is that everything needs to be sandboxed to be effective

**Comment by vasyugan** [comment]
the fix should be a trivial one-liner in the manifest, see https://github.com/vasyugan/im.riot.Riot/pull/1
